# Analyzing survey2ddi Outputs

This notebook demonstrates how to use the DDI XML and CSV outputs generated by `survey2ddi` using the built-in utility functions for easier data analysis with `pandas`.

In [1]:
import pandas as pd
from pathlib import Path
import sys
import os

# Add the project root to sys.path so we can import kobo2ddi
sys.path.append(os.path.abspath("../../"))

from kobo2ddi import read_variable_labels, apply_value_labels

# Paths to example files
xml_path = Path("101.xml")
csv_path = Path("101.csv")

## 1. Loading the Data

The CSV file contains the raw response codes. Its headers match the `name` attribute of `<var>` elements in the XML.

In [2]:
df = pd.read_csv(csv_path)
df.head()

  respondentname  age consent  thankyou
0          Alice   25     yes       NaN
1            Bob   30      no       NaN

## 2. Extracting Variable Labels

We use `read_variable_labels` to get human-readable titles for our questions directly from the DDI XML.

In [3]:
var_labels = read_variable_labels(xml_path)

print("Variable Labels:")
for name, labl in var_labels.items():
    print(f"{name}: {labl}")

Variable Labels:

## 3. Applying Value Labels

Categorical variables often use numeric codes (e.g., `1`, `2`) or short strings. We can use `apply_value_labels` to automatically map these to their labels (e.g., `Yes`, `No`) using the DDI metadata.

In [4]:
df_labeled = df.copy()
apply_value_labels(df_labeled, xml_path)

df_labeled.head()

  respondentname  age consent  thankyou
0          Alice   25     Yes       NaN
1            Bob   30      No       NaN

## 4. Visualization

Using the labels and cleaned data for plotting.

In [5]:
import matplotlib.pyplot as plt

column_to_plot = "q3"
df_labeled[column_to_plot].value_counts().plot(kind="bar")
plt.title(var_labels.get(column_to_plot, column_to_plot))
plt.ylabel("Count")
plt.show()

KeyError: 'q3'